// Mocks generated by Mockito 5.6.4 from annotations
// in okane_kore/test/core/firebase/auth_flow_test.dart.
// Do not manually edit this file.

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

class MockFirebaseAuth extends _i1.Mock implements _i2.FirebaseAuth {
  @override
  _i2.User? get currentUser => (super.noSuchMethod(Invocation.getter(#currentUser), returnValue: null) as _i2.User?);

  @override
  Stream<_i2.User?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(#authStateChanges, []),
        returnValue: Stream<_i2.User?>.empty(),
      ) as Stream<_i2.User?>);

  @override
  Future<_i2.UserCredential> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(#signInAnonymously, []),
        returnValue: _i1.Future<_i2.UserCredential>.value(_FakeUserCredential_0()),
      ) as Future<_i2.UserCredential>);

  @override
  Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(#signOut, []),
        returnValue: Future<void>.value(),
      ) as Future<void>);
}

class MockUserCredential extends _i1.Mock implements _i2.UserCredential {
  @override
  _i2.User? get user => (super.noSuchMethod(Invocation.getter(#user), returnValue: null) as _i2.User?);
}

class MockUser extends _i1.Mock implements _i2.User {
  @override
  String get uid => (super.noSuchMethod(Invocation.getter(#uid), returnValue: '') as String);

  @override
  String? get email => (super.noSuchMethod(Invocation.getter(#email), returnValue: null) as String?);

  @override
  String? get displayName => (super.noSuchMethod(Invocation.getter(#displayName), returnValue: null) as String?);

  @override
  bool get isAnonymous => (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false) as bool);
}

class _FakeUserCredential_0 extends _i1.Fake implements _i2.UserCredential {}
