// Mocks generated by Mockito 5.6.4 from annotations
// in okane_kore/test/features/household/data/social_contribution_service_test.dart.
// Do not manually edit this file.

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

class MockFirebaseFirestore extends _i1.Mock implements _i2.FirebaseFirestore {
  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(String path) =>
      (super.noSuchMethod(
        Invocation.method(#collection, [path]),
        returnValue: _FakeCollectionReference_0<Map<String, dynamic>>(),
      ) as _i2.CollectionReference<Map<String, dynamic>>);
}

class MockCollectionReference extends _i1.Mock
    implements _i2.CollectionReference<Map<String, dynamic>> {
  @override
  Future<_i2.QuerySnapshot<Map<String, dynamic>>> get() => (super.noSuchMethod(
        Invocation.method(#get, []),
        returnValue: _i1.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
          _FakeQuerySnapshot_0<Map<String, dynamic>>(),
        ),
      ) as Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  Stream<_i2.QuerySnapshot<Map<String, dynamic>>> snapshots() =>
      (super.noSuchMethod(
        Invocation.method(#snapshots, []),
        returnValue:
            Stream<_i2.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as Stream<_i2.QuerySnapshot<Map<String, dynamic>>>);
}

class MockQuerySnapshot extends _i1.Mock
    implements _i2.QuerySnapshot<Map<String, dynamic>> {
  @override
  List<_i2.QueryDocumentSnapshot<Map<String, dynamic>>> get docs =>
      (super.noSuchMethod(
        Invocation.getter(#docs),
        returnValue: <_i2.QueryDocumentSnapshot<Map<String, dynamic>>>[],
      ) as List<_i2.QueryDocumentSnapshot<Map<String, dynamic>>>);
}

class MockDocumentSnapshot extends _i1.Mock
    implements _i2.DocumentSnapshot<Map<String, dynamic>> {
  @override
  Map<String, dynamic>? get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: null,
      ) as Map<String, dynamic>?);

  @override
  bool get exists => (super.noSuchMethod(
        Invocation.getter(#exists),
        returnValue: false,
      ) as bool);
}

class _FakeCollectionReference_0<T> extends _i1.Fake
    implements _i2.CollectionReference<T> {}

class _FakeQuerySnapshot_0<T> extends _i1.Fake
    implements _i2.QuerySnapshot<T> {}

class _FakeDocumentSnapshot_0<T> extends _i1.Fake
    implements _i2.DocumentSnapshot<T> {}
