// File generated by the FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIt1e0hN8K3dl7HN2CoH_h95ztkNrgmg',
    appId: '1:216377882454:android:0d70a41d01bfac26d108f7',
    messagingSenderId: '216377882454',
    projectId: 'petit-works-apps-9029a',
    storageBucket: 'petit-works-apps-9029a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo80X9b2h8NpB1jxAwO75ELOYJyDMt1Yw',
    appId: '1:216377882454:ios:cd8bd9c019fa27ecd108f7',
    messagingSenderId: '216377882454',
    projectId: 'petit-works-apps-9029a',
    storageBucket: 'petit-works-apps-9029a.firebasestorage.app',
    iosBundleId: 'com.yourwish.okanekore',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
