// File generated by the FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIt1e0hN8K3dl7HN2CoH_h95ztkNrgmg',
    appId: '1:216377882454:android:0d70a41d01bfac26d108f7',
    messagingSenderId: '216377882454',
    projectId: 'petit-works-apps-9029a',
    storageBucket: 'petit-works-apps-9029a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-example-ios-key',
    appId: '1:216377882454:ios:example',
    messagingSenderId: '216377882454',
    projectId: 'petit-works-apps-9029a',
    storageBucket: 'petit-works-apps-9029a.firebasestorage.app',
    iosBundleId: 'com.example.okaneKore',
  );

  static FirebaseOptions get currentPlatform {
    return android;
  }
}
