import '../../features/quiz/domain/models/question.dart';

/// 貯蓄カテゴリの問題データ（家計管理・貯蓄・複利・預金）
List<Question> savingsQuestions() => [
      Question(
        id: 'q_savings_001',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '毎月の給料から10%を貯蓄すると、1年間でいくら貯まるでしょう？（月給30万円）',
        options: ['¥30万', '¥36万', '¥40万', '¥50万'],
        correctAnswerIndex: 1,
        explanation: '月給30万円 × 10% × 12ヶ月 = ¥36万円が1年間の貯蓄額です。',
      ),
      Question(
        id: 'q_savings_002',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '複利計算で、¥100万を年2%の利息で運用すると、2年後の金額は？',
        options: ['¥102万', '¥104万', '¥104.04万', '¥110万'],
        correctAnswerIndex: 2,
        explanation: '¥100万 × 1.02² = ¥104.04万。複利では利子にも利子がつきます。',
      ),
      Question(
        id: 'q_savings_003',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '「先取り貯蓄」とはどのような貯蓄方法でしょう？',
        options: [
          '余ったお金を貯める',
          '給料日に先に貯蓄額を取り分ける',
          'ボーナスだけ貯める',
          '借金を先に返す'
        ],
        correctAnswerIndex: 1,
        explanation: '先取り貯蓄は、給料が入ったらまず貯蓄分を別口座に移す方法。余りを貯めるより確実に貯まります。',
      ),
      Question(
        id: 'q_savings_004',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '生活防衛資金として一般的に推奨される金額の目安は？',
        options: ['生活費の1ヶ月分', '生活費の3〜6ヶ月分', '年収の2倍', '¥1000万'],
        correctAnswerIndex: 1,
        explanation: '万一の失業や病気に備え、生活費の3〜6ヶ月分を貯めておくと安心とされています。',
      ),
      Question(
        id: 'q_savings_005',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.medium,
        question: '「72の法則」で、年利6%の複利運用でお金が2倍になるのは約何年後？',
        options: ['約6年', '約12年', '約20年', '約36年'],
        correctAnswerIndex: 1,
        explanation: '72 ÷ 金利(%) ＝ 2倍になる年数。72 ÷ 6 = 12年。おおよその倍増期間がわかる便利な法則です。',
      ),
      Question(
        id: 'q_savings_006',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.medium,
        question: '普通預金と定期預金の一般的な違いとして正しいものは？',
        options: [
          '定期預金はいつでも引き出せる',
          '定期預金は普通預金より金利が高い傾向',
          '普通預金は元本保証がない',
          '定期預金は預金保険の対象外'
        ],
        correctAnswerIndex: 1,
        explanation: '定期預金は一定期間引き出さない代わりに、普通預金より金利が高めに設定されるのが一般的です。',
      ),
      Question(
        id: 'q_savings_007',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.medium,
        question: '毎月2万円を年利3%で20年間積み立てると、元本と運用益の合計はおよそいくら？',
        options: ['約480万円', '約560万円', '約656万円', '約800万円'],
        correctAnswerIndex: 2,
        explanation: '元本は2万×240ヶ月=480万円。複利運用でおよそ656万円に。時間を味方につける積立の力です。',
      ),
      Question(
        id: 'q_savings_008',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '銀行が破綻した場合、預金保険制度（ペイオフ）で保護される預金の上限は？',
        options: ['100万円まで', '500万円まで', '1金融機関1000万円まで（＋利息）', '無制限'],
        correctAnswerIndex: 2,
        explanation: 'ペイオフでは1金融機関あたり元本1000万円とその利息までが保護されます。分散預金がリスク対策になります。',
      ),
      Question(
        id: 'q_savings_009',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.hard,
        question: 'インフレ率が年2%のとき、金利0.001%の普通預金に預けたお金の「実質的な価値」はどうなる？',
        options: ['増える', 'ほぼ変わらない', '実質的に目減りする', '2倍になる'],
        correctAnswerIndex: 2,
        explanation: '物価上昇率が金利を上回ると、お金の実質価値は下がります。インフレ下では預金だけでは資産が目減りします。',
      ),
      Question(
        id: 'q_savings_010',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.medium,
        question: '家計管理でよく使われる「50・30・20ルール」の「20」が指すものは？',
        options: ['娯楽費', '固定費', '貯蓄・投資', '食費'],
        correctAnswerIndex: 2,
        explanation: '手取りの50%を必需品、30%を娯楽、20%を貯蓄・投資に回す目安。バランスの取れた家計配分の指針です。',
      ),
      Question(
        id: 'q_savings_011',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '家計簿をつける一番の目的は何でしょう？',
        options: [
          '税務署に提出するため',
          'お金の流れを把握し無駄を見つけるため',
          '銀行に見せるため',
          '家族に自慢するため'
        ],
        correctAnswerIndex: 1,
        explanation: '家計簿は収支を「見える化」し、使いすぎや固定費の無駄に気づくための道具です。',
      ),
      Question(
        id: 'q_savings_012',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.hard,
        question: '毎月の固定費削減が貯蓄に効果的とされる理由として最も適切なものは？',
        options: [
          '一度見直せば節約効果が毎月自動的に続くから',
          '固定費は金額が小さいから',
          '変動費より心理的に我慢が必要だから',
          '固定費は税金がかからないから'
        ],
        correctAnswerIndex: 0,
        explanation: 'スマホ料金や保険などの固定費は一度見直せば効果が継続。我慢を伴う変動費節約より持続的です。',
      ),
      Question(
        id: 'q_savings_013',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '「キャッシュレス決済」を家計管理に使うメリットとして正しいものは？',
        options: [
          '利用履歴が自動で残り支出を把握しやすい',
          '必ず出費が減る',
          '現金より必ずお得',
          'お金が増える'
        ],
        correctAnswerIndex: 0,
        explanation: 'キャッシュレスは履歴が自動記録され家計簿代わりに。ただし使いすぎには注意が必要です。',
      ),
      Question(
        id: 'q_savings_014',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.medium,
        question: '「固定費」に分類されるものは次のうちどれ？',
        options: ['家賃・通信費', '食費', '交際費', '旅行代'],
        correctAnswerIndex: 0,
        explanation: '毎月ほぼ一定額かかる家賃・通信費・保険料が固定費。金額が変わる食費や交際費は変動費です。',
      ),
      Question(
        id: 'q_savings_015',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.medium,
        question: '¥100万を年利1%と年利3%で30年運用した場合、差はおよそどのくらい？',
        options: ['ほとんど変わらない', '約10万円', '約100万円以上', '差はない'],
        correctAnswerIndex: 2,
        explanation: '1%なら約135万円、3%なら約243万円。複利では金利差が長期で大きな差を生みます。',
      ),
      Question(
        id: 'q_savings_016',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '「ボーナスをあてにした生活」が危険とされる理由は？',
        options: [
          'ボーナスは業績で減額・不支給の可能性があるから',
          'ボーナスは課税されないから',
          'ボーナスは必ず増えるから',
          'ボーナスは貯金できないから'
        ],
        correctAnswerIndex: 0,
        explanation: 'ボーナスは変動しやすい収入。月給の範囲で生活を組み立てるのが家計安定の基本です。',
      ),
      Question(
        id: 'q_savings_017',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.hard,
        question: '「ラテマネー」という言葉が示す考え方は？',
        options: [
          '少額の習慣的支出が積み重なると大きな額になること',
          'コーヒーは投資になること',
          'カフェ経営は儲かること',
          '高級品は資産になること'
        ],
        correctAnswerIndex: 0,
        explanation: '毎日のコーヒー1杯のような小さな出費も、年間では数万円に。無意識の習慣支出を見直す考え方です。',
      ),
      Question(
        id: 'q_savings_018',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.medium,
        question: '目的別に口座を分ける「口座の使い分け」の主な効果は？',
        options: [
          '生活費・貯蓄・特別費が混ざらず管理しやすい',
          '金利が2倍になる',
          '税金が安くなる',
          '手数料が無料になる'
        ],
        correctAnswerIndex: 0,
        explanation: '用途ごとに口座を分けると、貯蓄に手をつけにくくなり、支出も把握しやすくなります。',
      ),
      Question(
        id: 'q_savings_019',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.easy,
        question: '「無駄遣いを減らすコツ」として効果的なのは？',
        options: [
          '買う前に24時間考える習慣をつける',
          'セールなら必ず買う',
          '欲しいと思ったら即購入',
          'ポイントのために多く買う'
        ],
        correctAnswerIndex: 0,
        explanation: '衝動買いを防ぐには「一晩置く」のが有効。本当に必要か冷静に判断できます。',
      ),
      Question(
        id: 'q_savings_020',
        category: QuizCategory.savings,
        difficulty: QuizDifficulty.hard,
        question: '「機会費用」の考え方に最も近いものは？',
        options: [
          'あるものを選ぶと、選ばなかった選択肢の価値を失うこと',
          '買い物にかかる交通費',
          '銀行の手数料',
          '商品の定価'
        ],
        correctAnswerIndex: 0,
        explanation: '機会費用とは「他を選べば得られたはずの価値」。時間やお金の使い道を考える上で重要な概念です。',
      ),
    ];
