import '../../features/quiz/domain/models/question.dart';

/// 税金カテゴリの問題データ（所得税・住民税・控除・ふるさと納税・NISA/iDeCo税制）
List<Question> taxQuestions() => [
      Question(
        id: 'q_tax_001',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: 'ふるさと納税の控除上限額を決める主な指標は何ですか？',
        options: ['収入（所得）', '年齢', '居住地の人口', '好きな自治体の数'],
        correctAnswerIndex: 0,
        explanation: 'ふるさと納税の控除上限額は、年収（所得）と家族構成によって決まります。',
      ),
      Question(
        id: 'q_tax_002',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: 'ふるさと納税で自己負担となる金額は原則いくらでしょう？',
        options: ['0円', '2,000円', '寄付額の10%', '5,000円'],
        correctAnswerIndex: 1,
        explanation: '上限額の範囲内なら、自己負担は原則2,000円のみ。残りは所得税・住民税から控除されます。',
      ),
      Question(
        id: 'q_tax_003',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: '給与から天引きされる「所得税」と「住民税」。住民税は主に何に使われる？',
        options: ['国の予算', '住んでいる自治体の行政サービス', '年金', '会社の経費'],
        correctAnswerIndex: 1,
        explanation: '住民税は都道府県・市区町村に納め、ゴミ収集や学校など地域の行政サービスに使われます。',
      ),
      Question(
        id: 'q_tax_004',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: '「所得控除」と「税額控除」の違いとして正しいものは？',
        options: [
          '両者は全く同じもの',
          '所得控除は課税対象額を減らし、税額控除は税額そのものを減らす',
          '税額控除は所得を増やす',
          '所得控除は法人だけが使える'
        ],
        correctAnswerIndex: 1,
        explanation: '所得控除は税金がかかる前の所得を減らし、税額控除は計算後の税額から直接差し引きます。税額控除の方が減税効果が大きいことが多いです。',
      ),
      Question(
        id: 'q_tax_005',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: '会社員が医療費控除を受けるために必要な手続きは？',
        options: ['年末調整だけでOK', '確定申告が必要', '手続き不要で自動適用', '会社に申請書を出すだけ'],
        correctAnswerIndex: 1,
        explanation: '医療費控除は年末調整では処理されず、自分で確定申告をする必要があります。',
      ),
      Question(
        id: 'q_tax_006',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: 'NISA（少額投資非課税制度）の最大のメリットは？',
        options: [
          '元本が保証される',
          '投資で得た利益に税金がかからない',
          '必ず儲かる',
          '手数料が無料になる'
        ],
        correctAnswerIndex: 1,
        explanation: '通常、投資利益には約20%課税されますが、NISA口座内の利益は非課税になります。',
      ),
      Question(
        id: 'q_tax_007',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: 'iDeCo（個人型確定拠出年金）の掛金は税制上どう扱われる？',
        options: [
          '全額が所得控除の対象',
          '課税対象になる',
          '半分だけ控除',
          '控除は一切ない'
        ],
        correctAnswerIndex: 0,
        explanation: 'iDeCoの掛金は全額が所得控除の対象。所得税・住民税が軽減される節税メリットがあります。',
      ),
      Question(
        id: 'q_tax_008',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.hard,
        question: '日本の所得税で採用されている、所得が高いほど税率が上がる仕組みを何という？',
        options: ['一律課税', '累進課税', '逆進課税', '比例課税'],
        correctAnswerIndex: 1,
        explanation: '所得税は課税所得が増えるほど税率が上がる「累進課税」。5%〜45%の7段階に分かれています。',
      ),
      Question(
        id: 'q_tax_009',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: '2024年から始まった新NISAの「つみたて投資枠」の年間投資上限額は？',
        options: ['40万円', '120万円', '240万円', '360万円'],
        correctAnswerIndex: 1,
        explanation: '新NISAのつみたて投資枠は年120万円、成長投資枠は年240万円、合計で年360万円まで投資可能です。',
      ),
      Question(
        id: 'q_tax_010',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: '会社員の「給与所得控除」とはどのようなもの？',
        options: [
          '給与に対して自動的に差し引かれる必要経費のような控除',
          '会社が支払うボーナス',
          '残業代の一種',
          '交通費の非課税分'
        ],
        correctAnswerIndex: 0,
        explanation: '給与所得控除は、会社員の「みなし経費」。収入に応じて一定額が自動的に控除されます。',
      ),
      Question(
        id: 'q_tax_011',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.hard,
        question: '課税所得が同じでも、「扶養控除」があると税額はどうなる？',
        options: ['変わらない', '課税所得が減り税額も減る', '税額が増える', '扶養は税金と無関係'],
        correctAnswerIndex: 1,
        explanation: '扶養親族がいると扶養控除で課税所得が減り、結果的に所得税・住民税が軽くなります。',
      ),
      Question(
        id: 'q_tax_012',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: '消費税は「間接税」に分類されます。間接税の特徴は？',
        options: [
          '税を負担する人と納める人が異なる',
          '所得に応じて税率が変わる',
          '会社だけが払う',
          '毎年確定申告が必要'
        ],
        correctAnswerIndex: 0,
        explanation: '消費税は消費者が負担し、事業者が納税します。負担者と納税者が異なるのが間接税の特徴です。',
      ),
      Question(
        id: 'q_tax_013',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: '「年末調整」とは何をする手続き？',
        options: [
          '1年間の所得税の過不足を精算する',
          '来年の給料を決める',
          'ボーナスを計算する',
          '有給休暇を精算する'
        ],
        correctAnswerIndex: 0,
        explanation: '年末調整は、毎月天引きされた所得税と本来の税額の差を年末に精算する手続きです。',
      ),
      Question(
        id: 'q_tax_014',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: '住宅ローンを組んだ人が受けられる「住宅ローン控除」は何を軽減する？',
        options: ['所得税・住民税', '消費税', '固定資産税', '相続税'],
        correctAnswerIndex: 0,
        explanation: '住宅ローン控除は、年末のローン残高に応じて所得税（引ききれない分は住民税）が控除される制度です。',
      ),
      Question(
        id: 'q_tax_015',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: 'iDeCo（個人型確定拠出年金）の大きな注意点として正しいものは？',
        options: [
          '原則60歳まで引き出せない',
          'いつでも自由に引き出せる',
          '毎月自動で利益が確定する',
          '加入後は解約できない'
        ],
        correctAnswerIndex: 0,
        explanation: 'iDeCoは老後資金づくりのための制度のため、原則として60歳になるまで資産を引き出すことができません。加入前にこの流動性の低さを理解しておくことが重要です。',
      ),
      Question(
        id: 'q_tax_016',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.hard,
        question: '副業の所得が年間いくらを超えると、原則確定申告が必要になる？',
        options: ['20万円', '10万円', '48万円', '103万円'],
        correctAnswerIndex: 0,
        explanation: '給与所得者は、給与以外の所得が年20万円を超えると原則確定申告が必要です。',
      ),
      Question(
        id: 'q_tax_017',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.easy,
        question: '「源泉徴収票」に記載されている内容として正しいものは？',
        options: [
          '1年間の給与総額や納めた所得税額',
          '来年の昇給予定',
          '有給休暇の残日数',
          '会社の売上高'
        ],
        correctAnswerIndex: 0,
        explanation: '源泉徴収票には年間の収入・控除・納税額がまとまっています。確定申告やローン審査で使います。',
      ),
      Question(
        id: 'q_tax_018',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: 'ふるさと納税の「ワンストップ特例制度」を使える条件は？',
        options: [
          '確定申告が不要な給与所得者で寄付先が5自治体以内',
          '寄付先が何自治体でもよい',
          '自営業者であること',
          '寄付額が100万円以上'
        ],
        correctAnswerIndex: 0,
        explanation: 'ワンストップ特例は、確定申告不要な会社員などが寄付先5自治体以内の場合に使える簡易手続きです。',
      ),
      Question(
        id: 'q_tax_019',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.hard,
        question: '新NISAで得た配当金や売却益にかかる税金は？',
        options: ['非課税（0円）', '約20%', '約10%', '約30%'],
        correctAnswerIndex: 0,
        explanation: '通常は約20%課税されますが、NISA口座内の利益は非課税。これがNISA最大のメリットです。',
      ),
      Question(
        id: 'q_tax_020',
        category: QuizCategory.tax,
        difficulty: QuizDifficulty.medium,
        question: '「扶養内で働く」ときによく聞く「123万円の壁」は主に何に関係する？',
        options: [
          '所得税がかかり始める目安',
          '住民票の登録',
          '年金の受給額',
          '健康診断の要否'
        ],
        correctAnswerIndex: 0,
        explanation: '給与収入123万円を超えると本人に所得税がかかり始めます。2024年の税制改正により、従来の103万円から123万円に引き上げられました。',
      ),
    ];
